# Development environment configuration
app:
  name: "spring-cloud-integration"
  version: "2.0.0-dev"
  environment: "dev"
  configSource: "github-dev-profile"
  debug: true

# Development feature flags
features:
  github-config: true
  vault-secrets: true
  config-server: true

# Development logging
logging:
  level:
    com.example: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
    root: INFO

# Development settings
settings:
  pagination:
    defaultPageSize: 5
  cache:
    ttl: 60        
