# Production environment configuration
app:
  message: "Production config from GitHub!"
  environment: "production"
  debug: false

# Production-specific settings  
features:
  github-config: true
  prod-mode: true
  debug-logging: false

logging:
  level:
    com.example: WARN
    org.springframework.cloud.config: WARN