# Production environment configuration
app:
  name: "Spring Cloud Integration"
  version: "2.0.0"
  environment: "production"
  configSource: "github-prod-profile"
  debug: false

# Production feature flags (conservative)
features:
  github-config: true
  vault-secrets: true
  config-server: true
  user-management: true
  advanced-search: true
  premium-features: true
  beta-testing: false
  performance-monitoring: true

# Production settings
settings:
  pagination:
    defaultPageSize: 50
    maxPageSize: 500
  cache:
    ttl: 7200
    maxSize: 5000
  api:
    timeout: 15
    retries: 5

# Production logging (minimal)
logging:
  level:
    com.example: WARN
    org.springframework.cloud.config: WARN
    root: ERROR