# Development environment configuration
app:
  message: "Development config from GitHub!"
  environment: "development"
  debug: true

# Development-specific settings
features:
  github-config: true
  dev-mode: true
  debug-logging: true

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud.config: DEBUG