# Production Environment Configuration
app:
  environment: "production"
  debug: false
  configSource: "github-prod-profile"

# Production Feature Flags (conservative)
features:
  # Stable features only
  advanced-search: true
  premium-features: true
  beta-testing: false  # Disable beta in production
  mobile-app: false    # Not ready for production
  
  # Production optimizations
  performance-monitoring: true
  error-tracking: true
  analytics: true

# Production Settings
settings:
  pagination:
    defaultPageSize: 50
    maxPageSize: 500
  cache:
    ttl: 7200  # Longer cache in production
    maxSize: 5000
  api:
    timeout: 15
    retries: 5

# Production Logging (minimal)
logging:
  level:
    com.example: WARN
    org.springframework.cloud.config: WARN
    org.springframework.security: WARN
    root: ERROR

# Production Database
database:
  connection:
    maxPoolSize: 50  # Larger pool for production
    minPoolSize: 10
  jpa:
    showSql: false
    ddlAuto: "none"  # Never modify schema in production

# Production External Services
external:
  services:
    weatherApi:
      timeout: 3000  # Faster timeout in production
    newsApi:
      timeout: 5000