# Default configuration from GitHub

# Logging configuration
logging:
  level:
    com.example: INFO
    org.springframework.cloud.config: INFO
    root: WARN

# Development settings
settings:
  pagination:
    defaultPageSize: 10
  cache:
    ttl: 60    
