spring:
  application:
    name: spring-cloud-integration
  profiles:
    active: dev
server:
  port: 8081

# Application specific properties
app:
  message: "Hello from Spring Cloud Integration Dev!"

logging:
  level:
    com.example: DEBUG
    io.getunleash: DEBUG