# Default configuration from GitHub
app:
  message: "Configuration loaded from GitHub!"
  version: "1.0.0"
  environment: "default"

# GitHub-managed feature flags
features:
  github-config: true
  centralized-config: true
  version-controlled: true

# Logging configuration
logging:
  level:
    com.example: INFO
    org.springframework.cloud.config: DEBUG